server:
  port: 8081


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 600600
      url: jdbc:mysql://localhost:3306?serverTimezone=UTC # 时区配置 mysql5 和 mysql8的区别
      username: root
